kind: Service
apiVersion: v1
metadata:
  #Service name
  name: hs-webapi-svc
spec:
  selector:
    app: hs-webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
